# Generated by Django 2.0.5 on 2018-05-24 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='server',
            name='port',
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('key',)},
        ),
    ]
