# Generated by Django 2.0.5 on 2018-05-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20180523_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='token',
        ),
    ]
