# Generated by Django 2.0.5 on 2018-05-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        ('players', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('stage', models.IntegerField()),
                ('mode', models.SmallIntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('completions', models.IntegerField(blank=True, null=True)),
                ('enter_velocity', models.CharField(blank=True, max_length=40, null=True)),
                ('exit_velocity', models.CharField(blank=True, max_length=40, null=True)),
                ('avg_velocity', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='times.Time')),
                ('time', models.FloatField()),
                ('stage_time', models.FloatField()),
                ('checkpoint', models.IntegerField()),
                ('enter_velocity', models.CharField(blank=True, max_length=40, null=True)),
                ('exit_velocity', models.CharField(blank=True, max_length=40, null=True)),
                ('avg_velocity', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='time',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Course'),
        ),
        migrations.AddField(
            model_name='time',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='time',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servers.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together={('course', 'player', 'stage')},
        ),
        migrations.AlterIndexTogether(
            name='time',
            index_together={('course', 'stage')},
        ),
    ]
