# Generated by Django 2.0.5 on 2018-05-24 01:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('level', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
    ]
