# Generated by Django 2.0.5 on 2018-05-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
