# Generated by Django 2.0.5 on 2018-05-28 05:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('first_used', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('auth', models.CharField(max_length=64, unique=True)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('first_login', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('connections', models.IntegerField(blank=True, default=0)),
                ('hours_played', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ip_addresses', to='players.Player'),
        ),
    ]
