# Generated by Django 2.0.5 on 2018-05-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20180524_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='players.Player'),
        ),
    ]
